import type { ContractAnalysisDTO } from '@/types/api';

export const demoAnalysis: ContractAnalysisDTO = {
    originContent: [
        '<h1>전 속 계 약 서</h1>',
        '<p>본 계약은 (주)에스엠엔터테인먼트(이하 갑이라 한다)와 가수/연기자 동방신기(이하 을이라 한다) 사이의 연예활동 전속 관리에 관한 제반 사항을 규정함을 목적으로 한다.</p>',
        '<h2>제2조 (계약기간)</h2>',
        '<p>본 계약기간은 최초 계약일부터 시작하여 을의 연예활동 데뷔일로부터 13년째 되는 날 종료하기로 한다.</p>',
        '<h2>제3조 (권리의 양도)</h2>',
        '<p>을은 저작물에 대한 복제권, 음반권, 배포권, 2차적 저작물 작성권 등 모든 권리를 갑에게 양도한다.</p>',
        '<h2>제9조 (이익금의 분배)</h2>',
        '<p>온라인 음원 유통 및 해외 제작 음반의 경우 순수익의 10%를 지급한다.</p>',
        '<h2>제11조 (위약과 손해배상)</h2>',
        '<p>손해배상액은 총 투자액의 3배와 잔여 계약기간 동안의 일실이익의 2배를 합산한 금액으로 한다.</p>',
    ].join('\n'),
    contractId: 'demo-contract',
    analysisId: 'demo-analysis',
    title: '원룸 임대차계약서',
    contractType: 'ENTERTAINMENT',
    createdAt: new Date().toISOString(),
    summary: '과도한 계약기간, 권리양도, 수익분배, 손해배상 조항에서 주요 위험이 발견되었습니다.',
    analysisStatus: 'completed',
    toxicCount: 4,
    ocrBlocks: [
        {
            id: 'demo-0',
            category: 'heading',
            content: '<h1>전 속 계 약 서</h1>',
            tagIdx: 0,
        },
        {
            id: 'demo-1',
            category: 'paragraph',
            content: '<p>본 계약은 (주)에스엠엔터테인먼트와 가수/연기자 동방신기 사이의 연예활동 전속 관리에 관한 제반 사항을 규정함을 목적으로 한다.</p>',
            tagIdx: 1,
        },
        {
            id: 'demo-2',
            category: 'paragraph',
            content: '<h2>제2조 (계약기간)</h2><p>본 계약기간은 최초 계약일부터 시작하여 을의 연예활동 데뷔일로부터 <strong>13년째 되는 날</strong> 종료하기로 한다.</p>',
            tagIdx: 2,
        },
        {
            id: 'demo-3',
            category: 'paragraph',
            content: '<h2>제3조 (권리의 양도)</h2><p>을은 저작물에 대한 복제권, 음반권, 배포권, 2차적 저작물 작성권 등 <strong>모든 권리를 갑에게 양도한다</strong>.</p>',
            tagIdx: 3,
        },
        {
            id: 'demo-4',
            category: 'paragraph',
            content: '<h2>제9조 (이익금의 분배)</h2><p>온라인 음원 유통 및 해외 제작 음반의 경우 <strong>순수익의 10%</strong>를 지급한다.</p>',
            tagIdx: 4,
        },
        {
            id: 'demo-5',
            category: 'paragraph',
            content: '<h2>제11조 (위약과 손해배상)</h2><p>손해배상액은 <strong>총 투자액의 3배와 잔여 계약기간 동안의 일실이익의 2배</strong>를 합산한 금액으로 한다.</p>',
            tagIdx: 5,
        },
    ],
    riskdetectorCommentary: {
        overallComment: '과도한 계약기간, 포괄적인 권리양도, 낮은 수익분배, 과도한 손해배상 조항이 함께 포함되어 협상상 불리한 계약입니다.',
        warningComment: '대중문화예술인 표준전속계약서 기준과 비교하면 계약기간 13년은 과도합니다 / 저작권 관련 권리를 전면 양도시키는 조항은 권리 제한 폭이 큽니다 / 손해배상 예정액이 실제 손해를 넘어서면 불공정 조항으로 다툴 여지가 있습니다.',
        advice: '계약기간을 7년 이내로 줄이고 갱신 조건을 별도로 두는 것이 좋습니다 / 저작권 양도 범위를 구체적으로 한정하고 2차적 저작물 작성권은 별도 동의 조항으로 분리하세요 / 손해배상은 실제 발생 손해를 기준으로 조정하는 문구가 필요합니다.',
    },
    toxics: [
        {
            title: '과도한 계약기간',
            clause: '본 계약기간은 최초 계약일부터 시작하여 을의 연예활동 데뷔일로부터 13년째 되는 날 종료하기로 한다.',
            reason: '장기간 전속계약은 직업 선택과 활동 자유를 과도하게 제한할 수 있습니다.',
            reasonReference: '대중문화예술인 표준전속계약서 및 관련 공정거래 기준에서는 장기 전속계약의 불공정성을 엄격하게 봅니다.',
            sourceContractTagIdx: 2,
            warnLevel: 3,
        },
        {
            title: '포괄적 권리양도',
            clause: '을은 저작물에 대한 복제권, 음반권, 배포권, 2차적 저작물 작성권 등 모든 권리를 갑에게 양도한다.',
            reason: '창작물 권리 전체를 일괄 양도하도록 하면 향후 사용 범위와 수익 귀속이 불명확해집니다.',
            reasonReference: '저작권법상 권리 양도는 범위와 대상을 명확히 특정하는 것이 안전합니다.',
            sourceContractTagIdx: 3,
            warnLevel: 3,
        },
        {
            title: '불공정한 수익분배',
            clause: '온라인 음원 유통 및 해외 제작 음반의 경우 순수익의 10%를 지급한다.',
            reason: '기여도와 시장 관행에 비해 수익분배율이 낮으면 불공정한 정산 구조가 될 수 있습니다.',
            reasonReference: '문화체육관광부 표준계약서 가이드라인은 정산 기준과 배분율의 명확성을 강조합니다.',
            sourceContractTagIdx: 4,
            warnLevel: 2,
        },
        {
            title: '과도한 손해배상 예정',
            clause: '손해배상액은 총 투자액의 3배와 잔여 계약기간 동안의 일실이익의 2배를 합산한 금액으로 한다.',
            reason: '실제 손해보다 지나치게 큰 배상 예정액은 계약 해지를 사실상 막는 장치가 될 수 있습니다.',
            reasonReference: '민법상 손해배상 예정액이 부당히 과다하면 감액될 수 있습니다.',
            sourceContractTagIdx: 5,
            warnLevel: 3,
        },
    ],
};
