create schema if not exists prod;

create extension if not exists pgcrypto with schema extensions;

create table if not exists prod.users (
    id bigint generated by default as identity primary key,
    auth_user_id uuid unique,
    email varchar(255) unique not null,
    password varchar(255),
    name varchar(100),
    picture varchar(500),
    provider varchar(50) not null default 'supabase',
    created_at timestamp default now(),
    updated_at timestamp default now()
);

alter table prod.users add column if not exists auth_user_id uuid unique;
alter table prod.users add column if not exists password varchar(255);
alter table prod.users add column if not exists provider varchar(50) not null default 'supabase';

create table if not exists prod.contracts (
    id varchar(50) primary key,
    user_id bigint references prod.users(id) on delete set null,
    title varchar(500),
    contract_type varchar(50),
    guest_session_id varchar(100),
    s3_key_prefix varchar(500),
    created_at timestamp default now(),
    updated_at timestamp default now()
);

create table if not exists prod.ocr_content (
    id varchar(50) primary key,
    contract_id varchar(50) references prod.contracts(id) on delete cascade,
    content text,
    category varchar(100),
    tag_idx integer,
    created_at timestamp default now()
);

create table if not exists prod.contract_analyses (
    id varchar(50) primary key,
    contract_id varchar(50) references prod.contracts(id) on delete cascade,
    summary text,
    status varchar(50),
    process_status varchar(50),
    riskdetector_overall_comment text,
    riskdetector_warning_comment text,
    riskdetector_advice text,
    created_at timestamp default now(),
    updated_at timestamp default now()
);

create table if not exists prod.toxic_clauses (
    id varchar(50) primary key,
    analysis_id varchar(50) references prod.contract_analyses(id) on delete cascade,
    title varchar(500),
    clause text,
    reason text,
    reason_reference text,
    suggestion text,
    source_contract_tag_idx integer,
    warn_level integer,
    created_at timestamp default now()
);

create table if not exists prod.legal_tips (
    id bigint generated by default as identity primary key,
    source_id varchar(100) unique not null,
    category varchar(255) not null,
    question text not null,
    summary text,
    answer text not null,
    source_url text,
    view_count bigint default 0,
    created_at timestamp default now(),
    updated_at timestamp default now()
);

create table if not exists prod.legal_tip_bookmarks (
    id bigint generated by default as identity primary key,
    tip_id bigint references prod.legal_tips(id) on delete cascade,
    user_id bigint references prod.users(id) on delete cascade,
    guest_session_id varchar(100),
    created_at timestamp default now()
);

create unique index if not exists uq_legal_tip_bookmarks_user
    on prod.legal_tip_bookmarks(tip_id, user_id)
    where user_id is not null;

create unique index if not exists uq_legal_tip_bookmarks_guest
    on prod.legal_tip_bookmarks(tip_id, guest_session_id)
    where guest_session_id is not null;

create index if not exists idx_users_auth_user_id on prod.users(auth_user_id);
create index if not exists idx_contracts_user_id on prod.contracts(user_id);
create index if not exists idx_contracts_guest_session_id on prod.contracts(guest_session_id);
create index if not exists idx_ocr_content_contract_id on prod.ocr_content(contract_id);
create index if not exists idx_analyses_contract_id on prod.contract_analyses(contract_id);
create index if not exists idx_toxic_clauses_analysis_id on prod.toxic_clauses(analysis_id);
create index if not exists idx_legal_tips_category on prod.legal_tips(category);
create index if not exists idx_legal_tip_bookmarks_tip_id on prod.legal_tip_bookmarks(tip_id);
create index if not exists idx_legal_tip_bookmarks_user_id on prod.legal_tip_bookmarks(user_id);
create index if not exists idx_legal_tip_bookmarks_guest_session_id on prod.legal_tip_bookmarks(guest_session_id);

alter table prod.users enable row level security;
alter table prod.contracts enable row level security;
alter table prod.ocr_content enable row level security;
alter table prod.contract_analyses enable row level security;
alter table prod.toxic_clauses enable row level security;
alter table prod.legal_tips enable row level security;
alter table prod.legal_tip_bookmarks enable row level security;

grant usage on schema prod to anon, authenticated, service_role;
grant all on all tables in schema prod to anon, authenticated, service_role;
grant all on all routines in schema prod to anon, authenticated, service_role;
grant all on all sequences in schema prod to anon, authenticated, service_role;

alter default privileges in schema prod grant all on tables to anon, authenticated, service_role;
alter default privileges in schema prod grant all on routines to anon, authenticated, service_role;
alter default privileges in schema prod grant all on sequences to anon, authenticated, service_role;

alter role authenticator set pgrst.db_schemas = 'public,storage,graphql_public,prod';
notify pgrst, 'reload config';
notify pgrst, 'reload schema';
